substitutions:
  _IMAGE: 'tekcm24'
  _JOB_NAME: 'tekcm24'
  _REGION: 'asia-northeast1'
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/$_IMAGE:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/$_IMAGE:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
#  - 'jobs'
  - 'deploy'
  - '$_JOB_NAME'
  - '--image'
  - 'gcr.io/${PROJECT_ID}/$_IMAGE:$COMMIT_SHA'
  - '--region'
  - '$_REGION'
images:
- gcr.io/${PROJECT_ID}/$_IMAGE:$COMMIT_SHA
options:
  dynamic_substitutions: true